package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWageAllPropertiesEquals(Wage expected, Wage actual) {
        assertWageAutoGeneratedPropertiesEquals(expected, actual);
        assertWageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWageAllUpdatablePropertiesEquals(Wage expected, Wage actual) {
        assertWageUpdatableFieldsEquals(expected, actual);
        assertWageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWageAutoGeneratedPropertiesEquals(Wage expected, Wage actual) {
        assertThat(expected)
            .as("Verify Wage auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWageUpdatableFieldsEquals(Wage expected, Wage actual) {
        assertThat(expected)
            .as("Verify Wage relevant properties")
            .satisfies(e -> assertThat(e.getCoefficients()).as("check coefficients").isEqualTo(actual.getCoefficients()))
            .satisfies(e -> assertThat(e.getBaseSalary()).as("check baseSalary").isEqualTo(actual.getBaseSalary()))
            .satisfies(e -> assertThat(e.getAllowance()).as("check allowance").isEqualTo(actual.getAllowance()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWageUpdatableRelationshipsEquals(Wage expected, Wage actual) {
        // empty method
    }
}
